# Load packages
```{r}
library(tidyverse)
library(base)
library(patchwork)
library(scales)
library(ggridges)
library(patchwork)
library(ggseqlogo)
library(dplyr)
library(table1)
```

## Clean data

```{r}
#copy paste
rhc_clean <- rhc_data |> 
  bind_cols() |> 
  as_tibble() 

# convert death string to binary: 1 = dead 0 = alive
rhc_clean <- rhc_clean |> 
  mutate(death = case_when(
  death == "No" ~ 0,
  death == "Yes" ~ 1))

#round age to the nearest whole number
rhc_clean <- rhc_clean |> rename(weight = wtkilo1) |> 
                          mutate(age = round(age, 0),
                                 weight = round(weight, 0),
                                 edu = round(edu, 0)) 

#change Ptid to ID and move to first spot
rhc_clean <- rhc_clean |> 
  rename(ID = "ptid") |> relocate("ID")

# Modify the column names to remove "1" and "hx"
colnames(rhc_clean) <- str_replace_all(colnames(rhc_clean),"1", "") |> 
                       str_replace_all("hx", "")

#select(-"cat1")

rhc_clean

          

```

## Save data

```{r}
# Write the data to disk
write_csv(x = rhc_clean,
          file = "data/rhc_clean.csv")

```

## Comments
```{r}

#what do we do about date of last contact when looking at dead vs live

#Delete all attributes when we know which ones we do not use

```








