```{r}
library(ggplot2)
library(table1)
```
Table1
```{r}

rhc_clean |> mutate(sex = factor(sex),
                    swang1 = factor(swang1),
                    death = factor(death)) |> 
  table1(x = formula(~ sex + age + race + swang1| death),
         data = _)


```
```{r}
rhc_clean |> count(death, swang1) |> 
  ggplot(aes(x = swang1, y = n, fill = death))+
  geom_col(alpha = 1,
           color="pink") +
  labs(x = 'swang',
       y = 'n') +
  theme(axis.text.x = element_text(angle = 20, hjust = 1))
```


  

```{r}

subHX <- rhc_clean |> select(ends_with("hx"))
subHX <- subHX |> left_join(rhc_clean, join_by("death"))
  
subHX <- subHX |> pivot_longer(everything(),
                      names_to = "variables",
                      values_to = "values") 
ggplot(data = subHX, 
       mapping = aes( x = variables,
                      y = values)) + 
      geom_boxplot() 


library(tidyverse)

subHX |> 
  group_by(names, values) |> 
  summarise(count = n()) |> 
  pivot_wider(names_from = value, values_from = count, names_prefix = "count_")


rhc_clean |> View()
```
```{r}

gravier_clean_aug_long <- gravier_clean_aug |> 
    pivot_longer(cols = !early_metastasis,
                names_to = "gene",
                values_to = "log2_expr_level")



subHX |>
  ggplot(aes(x = chfhx)) +
  geom_bar()
subHX |>
  count(chfhx)
# B
subHX |>
  count(chfhx) |>
  ggplot(aes(x = chfhx, y = n)) +
  geom_col()
```

What diseases lead to getting RHC

What diseases lead to death even when getting RHC

What 