<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.475">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Logistic modelling</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="08_logistic_modelling_files/libs/clipboard/clipboard.min.js"></script>
<script src="08_logistic_modelling_files/libs/quarto-html/quarto.js"></script>
<script src="08_logistic_modelling_files/libs/quarto-html/popper.min.js"></script>
<script src="08_logistic_modelling_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="08_logistic_modelling_files/libs/quarto-html/anchor.min.js"></script>
<link href="08_logistic_modelling_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="08_logistic_modelling_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="08_logistic_modelling_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="08_logistic_modelling_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="08_logistic_modelling_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Logistic modelling</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="logistic-modelling" class="level2">
<h2 class="anchored" data-anchor-id="logistic-modelling">Logistic modelling</h2>
<p>The Aps1 is the APACHE score, which is a score given to patients in the ICU based on their vital scores, age and overall health, this score estimates the mortality of the patient based on how ill they are.</p>
<p>Usually this ranges from 0-71, but in this data set the min and max are 3-147, this is probably because the scoring system has been changed since the data was created.</p>
<p>We wish to model what scores indicates death and what scores indicate you will survive for the APACHE score.</p>
<p>As the value death is a binary value we choose the logistic binomial model to try and fit the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.3     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(base)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'scales'

The following object is masked from 'package:purrr':

    discard

The following object is masked from 'package:readr':

    col_factor</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggridges)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggseqlogo)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(table1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'table1'

The following objects are masked from 'package:base':

    units, units&lt;-</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(purrr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Load data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>rhc_aug <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"../data/rhc_aug.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 5612 Columns: 53
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (13): cat1, cat2, ca, sex, dth30, dnr1, ninsclas, race, income, Diagnosi...
dbl (40): ptID, death, cardiohx, chfhx, dementhx, psychhx, chrpulhx, renalhx...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<p>First we see if there is a general pattern in the mean values of the APACHE scores.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Means of aps1 for each dignosis</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>rhc_aug <span class="sc">|&gt;</span> </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Diagnosis, death) <span class="sc">|&gt;</span> </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mu=</span><span class="fu">mean</span>(aps1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Diagnosis'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 21 × 3
# Groups:   Diagnosis [11]
   Diagnosis          death    mu
   &lt;chr&gt;              &lt;dbl&gt; &lt;dbl&gt;
 1 card                   0  45.1
 2 card                   1  53.6
 3 gastr                  0  50.7
 4 gastr                  1  59.8
 5 hema                   0  58.7
 6 hema                   1  66.9
 7 meta                   0  52.3
 8 meta                   1  59.5
 9 multiple diagnosis     0  55.5
10 multiple diagnosis     1  62.2
# ℹ 11 more rows</code></pre>
</div>
</div>
<p>In all cases it is clear that the means of the APACHE scores are higher for those who end up dying.</p>
<section id="model-of-one-disease" class="level3">
<h3 class="anchored" data-anchor-id="model-of-one-disease"><strong>Model of one disease</strong></h3>
<p>First we try to do the prediction based on one of the diseases that was reason for admission (card).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Model of outcome of death based on aps1 for card patients.</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>aps1_card<span class="ot">&lt;-</span>rhc_aug <span class="sc">|&gt;</span> </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Diagnosis<span class="sc">==</span><span class="st">'card'</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>aps1_card_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">formula =</span> death <span class="sc">~</span> aps1,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> aps1_card, </span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>                      <span class="at">family=</span><span class="st">'binomial'</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>aps1_card_model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:  glm(formula = death ~ aps1, family = "binomial", data = aps1_card)

Coefficients:
(Intercept)         aps1  
   -0.75407      0.02571  

Degrees of Freedom: 1203 Total (i.e. Null);  1202 Residual
Null Deviance:      1593 
Residual Deviance: 1533     AIC: 1537</code></pre>
</div>
</div>
<p>The intercept means that each time the APACHE score increases by one, the chance of dying increases with 1/(1 + exp(-(-0.75407 + 0.02571 * x))).</p>
<p>An example is that for an APACHE score of 71 the risk of dying of cardiac disease is 74%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>aps1_card_model <span class="sc">|&gt;</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = death ~ aps1, family = "binomial", data = aps1_card)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -0.754069   0.177722  -4.243 2.21e-05 ***
aps1         0.025712   0.003472   7.406 1.30e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1592.5  on 1203  degrees of freedom
Residual deviance: 1532.8  on 1202  degrees of freedom
AIC: 1536.8

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>It seems that it is statistically significant.</p>
</section>
<section id="model-all-the-diagnoses" class="level3">
<h3 class="anchored" data-anchor-id="model-all-the-diagnoses">Model all the diagnoses</h3>
<p>We then choose to model the outcome for all the different admission diagnoses to see if we can predict the outcome of death by the APACHE score.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Create nested data.</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>aps1_data_nested <span class="ot">&lt;-</span> rhc_aug <span class="sc">|&gt;</span> </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Diagnosis) <span class="sc">|&gt;</span> </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nest</span>() <span class="sc">|&gt;</span> </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>aps1_data_nested</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 2
   Diagnosis          data                 
   &lt;chr&gt;              &lt;list&gt;               
 1 multiple diagnosis &lt;tibble [1,630 × 52]&gt;
 2 seps               &lt;tibble [411 × 52]&gt;  
 3 card               &lt;tibble [1,204 × 52]&gt;
 4 resp               &lt;tibble [1,150 × 52]&gt;
 5 renal              &lt;tibble [50 × 52]&gt;   
 6 hema               &lt;tibble [55 × 52]&gt;   
 7 gastr              &lt;tibble [565 × 52]&gt;  
 8 trauma             &lt;tibble [42 × 52]&gt;   
 9 neuro              &lt;tibble [445 × 52]&gt;  
10 meta               &lt;tibble [57 × 52]&gt;   
11 ortho              &lt;tibble [3 × 52]&gt;    </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#View one of them to test</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>aps1_data_nested <span class="sc">|&gt;</span> </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Diagnosis <span class="sc">==</span> <span class="st">"card"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
# A tibble: 1,204 × 52
    ptID cat1         cat2  ca    death cardiohx chfhx dementhx psychhx chrpulhx
   &lt;dbl&gt; &lt;chr&gt;        &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;
 1     3 MOSF w/Mali… MOSF… Yes       0        0     0        0       0        0
 2     5 MOSF w/Seps… &lt;NA&gt;  No        1        0     0        0       0        0
 3    12 ARF          &lt;NA&gt;  No        0        0     0        0       0        0
 4    13 MOSF w/Seps… &lt;NA&gt;  No        1        1     0        0       0        0
 5    15 ARF          &lt;NA&gt;  No        0        0     0        0       0        0
 6    23 CHF          &lt;NA&gt;  No        1        0     1        0       0        0
 7    25 CHF          &lt;NA&gt;  No        1        1     1        0       0        0
 8    26 ARF          &lt;NA&gt;  No        0        0     0        0       0        0
 9    29 Coma         &lt;NA&gt;  No        1        0     1        0       0        1
10    32 CHF          &lt;NA&gt;  No        0        1     1        0       0        0
# ℹ 1,194 more rows
# ℹ 42 more variables: renalhx &lt;dbl&gt;, liverhx &lt;dbl&gt;, gibledhx &lt;dbl&gt;,
#   malighx &lt;dbl&gt;, immunhx &lt;dbl&gt;, transhx &lt;dbl&gt;, amihx &lt;dbl&gt;, age &lt;dbl&gt;,
#   sex &lt;chr&gt;, edu &lt;dbl&gt;, surv2md1 &lt;dbl&gt;, das2d3pc &lt;dbl&gt;, t3d30 &lt;dbl&gt;,
#   dth30 &lt;chr&gt;, aps1 &lt;dbl&gt;, scoma1 &lt;dbl&gt;, meanbp1 &lt;dbl&gt;, wblc1 &lt;dbl&gt;,
#   hrt1 &lt;dbl&gt;, resp1 &lt;dbl&gt;, temp1 &lt;dbl&gt;, pafi1 &lt;dbl&gt;, alb1 &lt;dbl&gt;, hema1 &lt;dbl&gt;,
#   bili1 &lt;dbl&gt;, crea1 &lt;dbl&gt;, sod1 &lt;dbl&gt;, pot1 &lt;dbl&gt;, paco21 &lt;dbl&gt;, …</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Model of outcome of death based on aps1 for all diseases.</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>aps1_data_nested <span class="ot">&lt;-</span> aps1_data_nested <span class="sc">|&gt;</span> </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">model_object =</span> <span class="fu">map</span>(<span class="at">.x =</span> data,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>                              <span class="at">.f =</span> <span class="sc">~</span><span class="fu">glm</span>(<span class="at">formula =</span> death <span class="sc">~</span> aps1,                                         <span class="at">data =</span> .x, </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">family=</span><span class="st">'binomial'</span>)))</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>aps1_data_nested</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 3
   Diagnosis          data                  model_object
   &lt;chr&gt;              &lt;list&gt;                &lt;list&gt;      
 1 multiple diagnosis &lt;tibble [1,630 × 52]&gt; &lt;glm&gt;       
 2 seps               &lt;tibble [411 × 52]&gt;   &lt;glm&gt;       
 3 card               &lt;tibble [1,204 × 52]&gt; &lt;glm&gt;       
 4 resp               &lt;tibble [1,150 × 52]&gt; &lt;glm&gt;       
 5 renal              &lt;tibble [50 × 52]&gt;    &lt;glm&gt;       
 6 hema               &lt;tibble [55 × 52]&gt;    &lt;glm&gt;       
 7 gastr              &lt;tibble [565 × 52]&gt;   &lt;glm&gt;       
 8 trauma             &lt;tibble [42 × 52]&gt;    &lt;glm&gt;       
 9 neuro              &lt;tibble [445 × 52]&gt;   &lt;glm&gt;       
10 meta               &lt;tibble [57 × 52]&gt;    &lt;glm&gt;       
11 ortho              &lt;tibble [3 × 52]&gt;     &lt;glm&gt;       </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">#View the one for card diagnosis</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>aps1_data_nested <span class="sc">|&gt;</span>   </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Diagnosis <span class="sc">==</span> <span class="st">"card"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pull</span>(model_object) <span class="sc">|&gt;</span> </span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pluck</span>(<span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tidy</span>(<span class="at">conf.int =</span> <span class="cn">TRUE</span>,</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term        estimate std.error statistic  p.value conf.low conf.high
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)  -0.754    0.178       -4.24 2.21e- 5  -1.11     -0.408 
2 aps1          0.0257   0.00347      7.41 1.30e-13   0.0190    0.0326</code></pre>
</div>
</div>
<p>We exclude the ortho diagnosis as we earlier in other analysis saw, it only had 3 data points, which is probaly also the reason why this model fails on this value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Summerizes the model</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>aps1_data_nested <span class="ot">&lt;-</span> aps1_data_nested <span class="sc">|&gt;</span> </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Diagnosis) <span class="sc">|&gt;</span> </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Diagnosis <span class="sc">!=</span> <span class="st">"ortho"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">model_object_tidy =</span> <span class="fu">map</span>(<span class="at">.x =</span> model_object,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">.f =</span> <span class="sc">~</span><span class="fu">tidy</span>(<span class="at">conf.int =</span> <span class="cn">TRUE</span>,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>                                            <span class="at">conf.level =</span> <span class="fl">0.95</span>,</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>                                            <span class="at">x =</span> .x)))</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>aps1_data_nested</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 4
# Groups:   Diagnosis [10]
   Diagnosis          data                  model_object model_object_tidy
   &lt;chr&gt;              &lt;list&gt;                &lt;list&gt;       &lt;list&gt;           
 1 multiple diagnosis &lt;tibble [1,630 × 52]&gt; &lt;glm&gt;        &lt;tibble [2 × 7]&gt; 
 2 seps               &lt;tibble [411 × 52]&gt;   &lt;glm&gt;        &lt;tibble [2 × 7]&gt; 
 3 card               &lt;tibble [1,204 × 52]&gt; &lt;glm&gt;        &lt;tibble [2 × 7]&gt; 
 4 resp               &lt;tibble [1,150 × 52]&gt; &lt;glm&gt;        &lt;tibble [2 × 7]&gt; 
 5 renal              &lt;tibble [50 × 52]&gt;    &lt;glm&gt;        &lt;tibble [2 × 7]&gt; 
 6 hema               &lt;tibble [55 × 52]&gt;    &lt;glm&gt;        &lt;tibble [2 × 7]&gt; 
 7 gastr              &lt;tibble [565 × 52]&gt;   &lt;glm&gt;        &lt;tibble [2 × 7]&gt; 
 8 trauma             &lt;tibble [42 × 52]&gt;    &lt;glm&gt;        &lt;tibble [2 × 7]&gt; 
 9 neuro              &lt;tibble [445 × 52]&gt;   &lt;glm&gt;        &lt;tibble [2 × 7]&gt; 
10 meta               &lt;tibble [57 × 52]&gt;    &lt;glm&gt;        &lt;tibble [2 × 7]&gt; </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Unnest the summerized values</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>aps1_estimates <span class="ot">&lt;-</span> aps1_data_nested <span class="sc">|&gt;</span>  </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">unnest</span>(<span class="at">cols =</span> model_object_tidy)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>aps1_estimates</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 10
# Groups:   Diagnosis [10]
   Diagnosis   data     model_object term  estimate std.error statistic  p.value
   &lt;chr&gt;       &lt;list&gt;   &lt;list&gt;       &lt;chr&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
 1 multiple d… &lt;tibble&gt; &lt;glm&gt;        (Int… -0.163     0.178      -0.916 3.59e- 1
 2 multiple d… &lt;tibble&gt; &lt;glm&gt;        aps1   0.0180    0.00295     6.10  1.07e- 9
 3 seps        &lt;tibble&gt; &lt;glm&gt;        (Int… -1.30      0.425      -3.06  2.22e- 3
 4 seps        &lt;tibble&gt; &lt;glm&gt;        aps1   0.0292    0.00637     4.59  4.51e- 6
 5 card        &lt;tibble&gt; &lt;glm&gt;        (Int… -0.754     0.178      -4.24  2.21e- 5
 6 card        &lt;tibble&gt; &lt;glm&gt;        aps1   0.0257    0.00347     7.41  1.30e-13
 7 resp        &lt;tibble&gt; &lt;glm&gt;        (Int… -0.871     0.208      -4.18  2.90e- 5
 8 resp        &lt;tibble&gt; &lt;glm&gt;        aps1   0.0240    0.00391     6.15  7.92e-10
 9 renal       &lt;tibble&gt; &lt;glm&gt;        (Int…  0.429     1.05        0.407 6.84e- 1
10 renal       &lt;tibble&gt; &lt;glm&gt;        aps1   0.00959   0.0158      0.606 5.45e- 1
11 hema        &lt;tibble&gt; &lt;glm&gt;        (Int…  0.185     1.07        0.173 8.63e- 1
12 hema        &lt;tibble&gt; &lt;glm&gt;        aps1   0.0191    0.0168      1.14  2.55e- 1
13 gastr       &lt;tibble&gt; &lt;glm&gt;        (Int… -0.771     0.297      -2.60  9.37e- 3
14 gastr       &lt;tibble&gt; &lt;glm&gt;        aps1   0.0272    0.00528     5.15  2.61e- 7
15 trauma      &lt;tibble&gt; &lt;glm&gt;        (Int… -1.56      1.07       -1.45  1.47e- 1
16 trauma      &lt;tibble&gt; &lt;glm&gt;        aps1   0.0170    0.0198      0.857 3.91e- 1
17 neuro       &lt;tibble&gt; &lt;glm&gt;        (Int… -0.223     0.243      -0.919 3.58e- 1
18 neuro       &lt;tibble&gt; &lt;glm&gt;        aps1   0.0183    0.00631     2.90  3.70e- 3
19 meta        &lt;tibble&gt; &lt;glm&gt;        (Int… -0.552     0.760      -0.726 4.68e- 1
20 meta        &lt;tibble&gt; &lt;glm&gt;        aps1   0.0156    0.0129      1.21  2.26e- 1
# ℹ 2 more variables: conf.low &lt;dbl&gt;, conf.high &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Creates new dataframe with relevant columns for further analysis.</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>aps1_estimates <span class="ot">&lt;-</span> aps1_estimates <span class="sc">|&gt;</span> </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">select</span>(<span class="fu">c</span>(term,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>                                 Diagnosis, </span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>                                 p.value, </span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>                                 estimate, </span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>                                 conf.low, </span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>                                 conf.high))</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>aps1_estimates</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 6
# Groups:   Diagnosis [10]
   term        Diagnosis           p.value estimate conf.low conf.high
   &lt;chr&gt;       &lt;chr&gt;                 &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
 1 (Intercept) multiple diagnosis 3.59e- 1 -0.163   -0.513      0.185 
 2 aps1        multiple diagnosis 1.07e- 9  0.0180   0.0123     0.0238
 3 (Intercept) seps               2.22e- 3 -1.30    -2.15      -0.480 
 4 aps1        seps               4.51e- 6  0.0292   0.0170     0.0421
 5 (Intercept) card               2.21e- 5 -0.754   -1.11      -0.408 
 6 aps1        card               1.30e-13  0.0257   0.0190     0.0326
 7 (Intercept) resp               2.90e- 5 -0.871   -1.28      -0.466 
 8 aps1        resp               7.92e-10  0.0240   0.0165     0.0318
 9 (Intercept) renal              6.84e- 1  0.429   -1.65       2.56  
10 aps1        renal              5.45e- 1  0.00959 -0.0210     0.0422
11 (Intercept) hema               8.63e- 1  0.185   -1.94       2.35  
12 aps1        hema               2.55e- 1  0.0191  -0.0128     0.0544
13 (Intercept) gastr              9.37e- 3 -0.771   -1.36      -0.195 
14 aps1        gastr              2.61e- 7  0.0272   0.0171     0.0378
15 (Intercept) trauma             1.47e- 1 -1.56    -3.79       0.489 
16 aps1        trauma             3.91e- 1  0.0170  -0.0219     0.0574
17 (Intercept) neuro              3.58e- 1 -0.223   -0.704      0.250 
18 aps1        neuro              3.70e- 3  0.0183   0.00616    0.0309
19 (Intercept) meta               4.68e- 1 -0.552   -2.09       0.925 
20 aps1        meta               2.26e- 1  0.0156  -0.00895    0.0423</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Add significance determination value</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>aps1_estimates <span class="ot">&lt;-</span> aps1_estimates <span class="sc">|&gt;</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>                    </span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">q.value =</span> <span class="fu">map_dbl</span>(<span class="at">.x=</span>p.value,</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>                             <span class="at">.f =</span> <span class="sc">~</span><span class="fu">p.adjust</span>(.x, </span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>                                            <span class="at">method =</span> <span class="st">'fdr'</span>))) <span class="sc">|&gt;</span> </span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">is_significant =</span> <span class="fu">case_when</span>(q.value <span class="sc">&gt;</span> <span class="fl">0.05</span> <span class="sc">~</span> <span class="st">'No'</span>,</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>                                      q.value <span class="sc">&lt;=</span> <span class="fl">0.05</span> <span class="sc">~</span> <span class="st">'Yes'</span>))</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>aps1_estimates</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 8
# Groups:   Diagnosis [10]
   term   Diagnosis  p.value estimate conf.low conf.high  q.value is_significant
   &lt;chr&gt;  &lt;chr&gt;        &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;         
 1 (Inte… multiple… 3.59e- 1 -0.163   -0.513      0.185  3.59e- 1 No            
 2 aps1   multiple… 1.07e- 9  0.0180   0.0123     0.0238 1.07e- 9 Yes           
 3 (Inte… seps      2.22e- 3 -1.30    -2.15      -0.480  2.22e- 3 Yes           
 4 aps1   seps      4.51e- 6  0.0292   0.0170     0.0421 4.51e- 6 Yes           
 5 (Inte… card      2.21e- 5 -0.754   -1.11      -0.408  2.21e- 5 Yes           
 6 aps1   card      1.30e-13  0.0257   0.0190     0.0326 1.30e-13 Yes           
 7 (Inte… resp      2.90e- 5 -0.871   -1.28      -0.466  2.90e- 5 Yes           
 8 aps1   resp      7.92e-10  0.0240   0.0165     0.0318 7.92e-10 Yes           
 9 (Inte… renal     6.84e- 1  0.429   -1.65       2.56   6.84e- 1 No            
10 aps1   renal     5.45e- 1  0.00959 -0.0210     0.0422 5.45e- 1 No            
11 (Inte… hema      8.63e- 1  0.185   -1.94       2.35   8.63e- 1 No            
12 aps1   hema      2.55e- 1  0.0191  -0.0128     0.0544 2.55e- 1 No            
13 (Inte… gastr     9.37e- 3 -0.771   -1.36      -0.195  9.37e- 3 Yes           
14 aps1   gastr     2.61e- 7  0.0272   0.0171     0.0378 2.61e- 7 Yes           
15 (Inte… trauma    1.47e- 1 -1.56    -3.79       0.489  1.47e- 1 No            
16 aps1   trauma    3.91e- 1  0.0170  -0.0219     0.0574 3.91e- 1 No            
17 (Inte… neuro     3.58e- 1 -0.223   -0.704      0.250  3.58e- 1 No            
18 aps1   neuro     3.70e- 3  0.0183   0.00616    0.0309 3.70e- 3 Yes           
19 (Inte… meta      4.68e- 1 -0.552   -2.09       0.925  4.68e- 1 No            
20 aps1   meta      2.26e- 1  0.0156  -0.00895    0.0423 2.26e- 1 No            </code></pre>
</div>
</div>
<p>Plot of the model estimate aps1:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plots of the estimated variables</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>model_estimates <span class="ot">&lt;-</span> aps1_estimates <span class="sc">|&gt;</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> estimate,</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">y =</span> <span class="fu">fct_reorder</span>(Diagnosis,</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>                                       estimate))) <span class="sc">+</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>   <span class="fu">facet_wrap</span>(<span class="sc">~</span>term, <span class="at">scales =</span> <span class="st">"free_x"</span>)<span class="sc">+</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>is_significant)) <span class="sc">+</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbarh</span>(<span class="fu">aes</span>(<span class="at">xmin =</span> conf.low, </span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>                     <span class="at">xmax =</span> conf.high, <span class="at">color=</span>is_significant)) <span class="sc">+</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">values =</span> <span class="fu">c</span>(<span class="at">No =</span> <span class="st">"darkred"</span>, <span class="at">Yes =</span> <span class="st">"darkgoldenrod1"</span>),</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">'Estimates(95% CIs)'</span>, </span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">'Diseases'</span>,</span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">'The APACHE scores contribution to the prediction of death'</span>,</span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Significant"</span>)</span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="at">filename =</span> <span class="st">"08_model_estimates_7.png"</span>,</span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>       <span class="at">plot =</span> model_estimates,</span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a>       <span class="at">device =</span> <span class="st">"png"</span>,</span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a>       <span class="at">path =</span> <span class="st">"../results"</span>,</span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a>       <span class="at">scale =</span> <span class="dv">1</span>,</span>
<span id="cb33-24"><a href="#cb33-24" aria-hidden="true" tabindex="-1"></a>       <span class="at">limitsize =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Saving 7 x 5 in image</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>model_estimates</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="08_logistic_modelling_files/figure-html/unnamed-chunk-14-1.svg" class="img-fluid" width="672"></p>
</div>
</div>
<p>The higher the estimate of the slope , the higher the risk of dying is by each rise in the APACHE score.</p>
<p>Plot of the model estimates intercept:</p>
<p>Table with relevant model values for presentation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Table of relevant estimates</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>intercepts<span class="ot">&lt;-</span>aps1_estimates <span class="sc">|&gt;</span>   </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"(Intercept)"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Diagnosis, estimate, p.value) </span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>coefficients<span class="ot">&lt;-</span>aps1_estimates <span class="sc">|&gt;</span>   </span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"aps1"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Diagnosis, estimate)</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>model_variables<span class="ot">&lt;-</span> </span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(coefficients, intercepts, <span class="at">by =</span> <span class="st">"Diagnosis"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Intercept=</span>estimate.y) <span class="sc">|&gt;</span> </span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Coefficient=</span>estimate.x) <span class="sc">|&gt;</span> </span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a>model_variables</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 4
   Diagnosis          Coefficient Intercept   p.value
   &lt;chr&gt;                    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
 1 multiple diagnosis     0.0180     -0.163 0.359    
 2 seps                   0.0292     -1.30  0.00222  
 3 card                   0.0257     -0.754 0.0000221
 4 resp                   0.0240     -0.871 0.0000290
 5 renal                  0.00959     0.429 0.684    
 6 hema                   0.0191      0.185 0.863    
 7 gastr                  0.0272     -0.771 0.00937  
 8 trauma                 0.0170     -1.56  0.147    
 9 neuro                  0.0183     -0.223 0.358    
10 meta                   0.0156     -0.552 0.468    </code></pre>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>