Plots

```{r}
library(tidyverse)
library(base)
library(patchwork)
library(scales)
library(ggridges)
library(patchwork)
library(ggseqlogo)
library(dplyr)
library(table1)
```

```{r}
rhc_clean
```

Does the number of comorbidity diseases influence the risk of death?

```{r}
rhc_clean |>
  rowwise() |> 
  mutate(comorbidities=sum(c_across(cardiohx:amihx))) |> 
  
  ggplot(aes(x = comorbidities, fill=factor(death))) +
  geom_bar(position = "stack") +
  labs(title = "Risk of dying by number of comorbidities",
       x = "Number of comorbidities",
       y = "Number of patients") +
  scale_fill_manual(name= "Death", values = c("0" = "blue", "1" = "red")) +
  theme_minimal()
```

```{r}
rhc_clean |>
  rowwise() |> 
  mutate(comorbidities=sum(c_across(cardiohx:amihx))) |> 
  ggplot(aes(x = comorbidities, fill=factor(death))) +
  facet_wrap(~swang1)+
  geom_bar(position = "stack") +
  labs(title = "Risk of dying by number of comorbidities",
       x = "Number of comorbidities",
       y = "Number of patients") +
  scale_fill_manual(name= "Survival", values = c("0" = "#619CFF", "1" = "#F8766D"), labels= c('Dead', 'Alive')) +
  theme_minimal()
```

```{r}

#| label: function-for-words-to-binary
# Creating a generel function that can be used for yes and no columns
create_binary_column <- function(x) {
  ifelse(x == "Yes", 1, 
  ifelse(x == "No", 0, x))
}
rhc_clean |>
    
  mutate(across(resp:ortho, 
                ~create_binary_column(.))) |>
  pivot_longer(cols = resp:ortho,
               names_to = "Diagnosis",
               values_to = "Values")|> 
  filter(Values==1) 
   

 

```
