# Libraries 
```{r}
library(tidyverse)
library(base)
library(patchwork)
library(scales)
library(ggridges)
library(patchwork)
library(ggseqlogo)
library(dplyr)
library(table1)
```

```{r}
colnames(rhc_clean)
```

```{r}
rhc_clean |> select(age, sex, edu, race, income)
```
## Age

```{r}
# Histogram of Age
rhc_clean |>
  ggplot(aes(x = age)) +
  geom_histogram(binwidth = 5,
                 fill = "skyblue", color = "black") +
  labs(title = "Distribution of Age",
       x = "Age",
       y = "Frequency") +
  theme_minimal()

```
```{r}
# Death in different ages
rhc_clean |>
  ggplot(aes(x = age, 
             fill=factor(death))) +
  geom_bar() +
  labs(title = "Death in different ages",
       x = "Age",
       y = "Number of patients") +
  #scale_fill_manual(name= "Death", values = c("0" = "blue", "1" = "red")) +
  theme_minimal()



```

```{r}
## Percentage of DEATH by age
rhc_clean |> 
  group_by(age, death) |> 
  summarize(count = n()) |> 
  group_by(age) |> 
  mutate(percent = count / sum(count) * 100) |> 
  ungroup() |> 
  filter(death == 1) |> 
  select(age, percent)
```

## Gender

```{r}
# Death females vs. males
rhc_clean |>
  ggplot(aes(x = sex,
             fill=factor(death))) +
  geom_bar() +
  labs(title = "Death females vs. males",
       x = "Gender",
       y = "Number of patients") +
  #scale_fill_manual(name= "Death", values = c("0" = "blue", "1" = "red")) +
  theme_minimal()
```
```{r}
## Percentage of DEATH by gender
# rhc_clean |>
#   ggplot(aes(x = sex, 
#            fill = factor(death))) +
#   geom_bar(position = "fill", 
#            stat = "count") +
#   labs(title = "Percentage of Death in Females vs. Males",
#        x = "Gender",
#        y = "Percentage of patients",
#        fill = "Death Status") +
#   scale_y_continuous(labels = scales::percent_format()) +
#   theme_minimal()

rhc_clean |> 
  group_by(sex, death) |> 
  summarize(count = n()) |> 
  group_by(sex) |> 
  mutate(percent = count / sum(count) * 100) |> 
  ungroup() |> 
  filter(death == 1) |> 
  select(sex, percent)

```
## Race

```{r}
rhc_clean |> 
  ggplot(aes(x = race, 
             fill = as.factor(swang1))) +
  geom_bar() +
  labs(title = "Distribution of Race by RHC Status",
       x = "Race",
       y = "Count",
       fill = "RHC Status")
```

```{r}
rhc_clean |> 
  ggplot(aes(x = race, 
             fill=factor(death))) +
  geom_bar() +
  labs(title = "Death in race",
       x = "Race",
       y = "Count",
       fill = "Death")
```
```{r}
## Percentage of DEATH by race
rhc_clean |> 
  group_by(race, death) |> 
  summarize(count = n()) |> 
  group_by(race) |> 
  mutate(percent = count / sum(count) * 100) |> 
  ungroup() |> 
  filter(death == 1) |> 
  select(race, percent)
```

## Income

```{r}
rhc_clean |> 
  ggplot(aes(x = income, 
           fill = as.factor(swang1))) +
  geom_bar() +
  labs(title = "Distribution of Income by RHC Status",
       x = "Income",
       y = "Count",
       fill = "RHC Status")
```

```{r}
rhc_clean |> 
  ggplot(aes(x = income, 
             fill = factor(death))) +
  geom_bar() +
  labs(title = "Distribution of Income by Death",
       x = "Income",
       y = "Count",
       fill = "Death")
```
```{r}
## Percentage of DEATH by income
rhc_clean |> 
  group_by(income, death) |> 
  summarize(count = n()) |> 
  group_by(income) |> 
  mutate(percent = count / sum(count) * 100) |> 
  ungroup() |> 
  filter(death == 1) |> 
  select(income, percent)
```


## Education
```{r}
#'edu_group' based on the cut function
rhc_clean$edu_group <- cut(rhc_clean$edu, 
                           breaks = c(-Inf, 10, 20, Inf), 
                           labels = c("<10 years", "between 10-20 years", ">20 years"), 
                           include.lowest = TRUE,
                           na.rm = TRUE)

# rhc_clean |> 
#   select(edu_group)

```


```{r}
# Count of RHC by Education
rhc_clean |> 
  ggplot(aes((x = edu_group), 
             fill = as.factor(swang1))) +
  geom_bar() +
  labs(title = "Distribution of Education by RHC Status",
       x = "Education",
       y = "Count",
       fill = "RHC Status")

```
```{r}
## Percentage of DEATH by education
rhc_clean |> 
  group_by(edu_group, death) |> 
  summarize(count = n()) |> 
  group_by(edu_group) |> 
  mutate(percent = count / sum(count) * 100) |> 
  ungroup() |> 
  filter(death == 1) |> 
  select(edu_group, percent)
```


## Others


```{r}
rhc_clean |> 
  ggplot(aes(x = as.factor(sex), 
             y = age, 
             fill = as.factor(swang1))) +
  geom_bar(stat = "summary", fun = "mean", position = "dodge") +
  labs(title = "Average Age by Sex and RHC",
       x = "Sex",
       y = "Average Age",
       fill = "RHC Status")


```




```{r}
# Bar plot for Death by Race and RHC Status
rhc_clean |>
  ggplot(aes(x = race,
             fill = as.factor(death),
             group = as.factor(swang1))) +
  geom_bar(position = "dodge") +
  labs(title = "Death Count by Race and RHC Status",
       x = "Race",
       y = "Count",
       fill = "Death status") +
  facet_wrap(~swang1)
```
