

```{r}
#| label: function-for-words-to-binary
# Creating a generel function that can be used for yes and no columns
create_binary_column <- function(x) {
  ifelse(x == "Yes", 1, 
  ifelse(x == "No", 0, x))
}

convert_RHC <- function(df) {
  df %>%
    mutate(swang1 = case_when(
      swang1 == "No RHC" ~ 0,
      swang1 == "RHC" ~ 1
    ))
}


```


```{r}
#| label: plot-sex-against-age
rhc_clean |> 
  ggplot(aes(x = age, y = sex, color = death)) +
  geom_point()
```

```{r}
#| label: plot-surv-rate-vs-Cardi-Comor
# Assuming 'Cardiohx' is a binary indicator for cardiovascular comorbidity
rhc_aug |> 
  group_by(cardiohx) |> 
  summarise(survival_rate = mean(death)) |> 
  ggplot(aes(x = factor(cardiohx), 
             y = survival_rate, 
             fill = factor(cardiohx))) +
  geom_bar(stat = "identity") +
  labs(title = "Survival Rate by severe Cardiovascular Comorbidity",
       x = "Cardiovascular Comorbidity", 
       y = "Survival Rate") +
  guides(fill = guide_legend(title = "Disease Status"))

rhc_aug |> 
  group_by(Diagnosis) |> 
  count()

```


```{r}
#| label: meanbp-across-diagnosis-non-filtered
#| echo: false
#| output: false
rhc_aug |> 
  ggplot(aes(x = Diagnosis, 
             y = meanbp1,
             fill = factor(Values))) + #Is the factor(values) maybe unnecessary?
  geom_point(aes(color = factor(Values)), 
             position = position_dodge(0.8), 
             alpha = 0.5) +
  geom_boxplot(color = "black", 
               alpha = 0.5) +
  labs(title = "Mean blood pressure across all diagnosis",
       y = "Mean blood pressure") +
  guides(fill = guide_legend(title = "Diagnosis Status"),
         color = FALSE)
  
```
```{r}
#| label: meanbp-across-diagnosis-filtered
rhc_aug |> 
  ggplot(aes(x = Diagnosis, 
             y = meanbp1,
             fill = factor(Diagnosis))) +
  geom_point(aes(color = factor(Diagnosis)), 
             position = position_dodge(0.8), 
             alpha = 0.5) +
  geom_boxplot(color = "black", 
               alpha = 0.5) +
  labs(title = "Mean blood pressure across all diagnosis",
       y = "Mean blood pressure",
       color = "Diagonosis") +
  guides(fill = guide_legend(title = "Diagnosis Status"),
         color = FALSE) +
  theme(legend.key.height = unit(0.7, 'cm'),
        legend.key.width = unit(0.7, 'cm'))

  
```


```{r}
#| label: meanbp-diagnosis-separated-RHC
#| echo: false
#| output: false
rhc_aug|> 
  ggplot(aes(x = Diagnosis, 
             y = meanbp1,
             fill = factor(Values))) +
  geom_point(aes(color = as.factor(swang1)),
             position = position_dodge(0.8), 
             alpha = 0.5) +
  geom_boxplot(alpha = 0.5, outlier.shape = NA) +
  labs(title = "Mean blood pressure across all diagnosis",
       y = "Mean blood pressure",
       color = "RHC") +
  guides(fill = guide_legend(title = "Diagnosis Status",
         color = guide_legend(title = "RHC"))) +
  scale_fill_manual(values = c("1" = "#F8766D", 
                               "0" = "#619CFF"), 
                    labels = c("1" = "Yes", 
                               "0" = "No")) +
  scale_color_manual(values = c("1" = "#F8766D",
                                "0" = "#619CFF"), 
                     labels = c("1" = "Yes", 
                                "0" = "No"))
```

```{r}
#| label: meanbp-RHC-based-on-diagnosis
rhc_aug |> 
  ggplot(aes(x = Diagnosis, 
             y = meanbp1,
             fill = factor(swang1))) +
  geom_point(aes(color = as.factor(swang1)),
             position = position_dodge(0.8), 
             alpha = 0.5) +
  geom_boxplot(alpha = 0.5, 
               outlier.shape = NA) +
  labs(title = "Mean blood pressure across all diagnosis",
       y = "Mean blood pressure",
       color = "RHC") +
  guides(color = guide_legend(title = "RHC")) +
  scale_color_manual(values = c("1" = "#619CFF", 
                                "0" = "#F8766D"), 
                     labels = c("1" = "Yes", 
                                "0" = "No"))
```


```{r}
#| label: meanbp-RHC-based-on-primary-disease
rhc_clean |> 
    ggplot(aes(x = cat1, 
             y = meanbp1,
             fill = factor(swang1))) +
  geom_point(aes(color = cat1),
             position = position_dodge(0.8), 
             alpha = 0.5) +
  #geom_violin(alpha = 0.35, outlier.shape = NA) +
  geom_boxplot(alpha = 0.35, 
               outlier.shape = NA) +
  labs(title = "Mean blood pressure across all primary diseases",
       x = "Primary disease category",
       y = "Mean blood pressure",
       color = "Primary Disease Category") +
  guides(fill = guide_legend(title = "RHC")) +
  theme(axis.text.x = element_text(angle = 30,
                                   hjust = 1,
                                   vjust = 1))
```




































